# Generated by Django 2.2.7 on 2020-03-02 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='che',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='kind',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
