# Generated by Django 2.2.7 on 2020-03-02 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_auto_20200302_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='che',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rental', to='rental.Che'),
        ),
    ]
