# Generated by Django 2.2.7 on 2020-03-04 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0004_auto_20200302_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='kind',
            name='handling_time',
            field=models.FloatField(default=2, verbose_name='AVG handling time(minutes/box)'),
        ),
        migrations.AddField(
            model_name='kind',
            name='trans_time',
            field=models.FloatField(default=10, verbose_name='AVG transportation time(minutes/day)'),
        ),
    ]
