# Generated by Django 2.2.7 on 2020-03-25 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0005_auto_20200304_0900'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalDailySummary',
            fields=[
            ],
            options={
                'verbose_name': 'Rental Summary',
                'verbose_name_plural': 'Rental Summary',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('rental.rental',),
        ),
    ]
