# Generated by Django 2.2.7 on 2020-03-03 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssr', '0002_auto_20200302_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='ssr',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
