# Generated by Django 2.2.7 on 2020-03-25 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssr', '0003_ssr_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ssr',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
